name: Docker Compose CD with ClickHouse

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean old fixed-name containers
        run: |
          docker rm -f flask_app_web flask_app_clickhouse || true

      - name: Deploy application with Docker Compose
        run: |
          docker compose down --remove-orphans || true
          docker compose up -d --build
          docker ps

      - name: Check application
        run: |
          sleep 15
          curl -f http://localhost:5000

      - name: Check ClickHouse
        run: |
          docker compose exec -T clickhouse clickhouse-client \
            --user flaskuser \
            --password flaskpassword \
            --database flaskdb \
            --query "SELECT count() FROM visits;"