name: Docker Compose CD with ClickHouse

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, docker-lab]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy application with Docker Compose
        run: |
          docker compose -f docker-compose.yml down --remove-orphans || true
          docker compose -f docker-compose.yml up -d --build
          docker ps

      - name: Show logs
        run: |
          docker compose -f docker-compose.yml logs --tail=100

      - name: Check health endpoint
        run: |
          sleep 15
          curl -f http://localhost:5000/health

      - name: Check application
        run: |
          curl -f http://localhost:5000

      - name: Check ClickHouse
        run: |
          docker compose -f docker-compose.yml exec -T clickhouse clickhouse-client \
            --user flaskuser \
            --password flaskpassword \
            --database flaskdb \
            --query "SELECT count() FROM visits;"